//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using ParentalControl.Interface.Database;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Keyword class.
    /// </summary>
    public partial class Keyword : IKeyword
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        private Keyword()
        {
            this.WebLimitations = new HashSet<WebLimitation>();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Keyword"/> class.
        /// </summary>
        /// <param name="name">Name.</param>
        internal Keyword(string name)
            : this()
        {
            this.Name = name;
        }

        /// <inheritdoc/>
        public int ID { get; set; }

        /// <inheritdoc/>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets web limitations.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebLimitation> WebLimitations { get; set; }

        /// <summary>
        /// To string.
        /// </summary>
        /// <returns>String.</returns>
        public override string ToString()
        {
            return this.Name;
        }
    }
}