//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParentalControlEntities : DbContext
    {
        public ParentalControlEntities()
            : base("name=ParentalControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<ProgramSetting> ProgramSettings { get; set; }
        public virtual DbSet<TimeSetting> TimeSettings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WebSetting> WebSettings { get; set; }
    }
}
