//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Parental control entities class.
    /// </summary>
    public partial class ParentalControlEntities : DbContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParentalControlEntities"/> class.
        /// </summary>
        public ParentalControlEntities()
            : base("name=ParentalControlEntities")
        {
        }

        /// <summary>
        /// On model creating.
        /// </summary>
        /// <param name="modelBuilder">Model builder.</param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Gets or sets keywords.
        /// </summary>
        public virtual DbSet<Keyword> Keywords { get; set; }

        /// <summary>
        /// Gets or sets program limitations.
        /// </summary>
        public virtual DbSet<ProgramLimitation> ProgramLimitations { get; set; }

        /// <summary>
        /// Gets or sets users.
        /// </summary>
        public virtual DbSet<User> Users { get; set; }

        /// <summary>
        /// Gets or sets web limitations.
        /// </summary>
        public virtual DbSet<WebLimitation> WebLimitations { get; set; }
    }
}
