//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using ParentalControl.Interface.Database;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Program limitation class.
    /// </summary>
    public partial class ProgramLimitation : IProgramLimitation
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProgramLimitation"/> class.
        /// </summary>
        /// <param name="userID">UserID.</param>
        /// <param name="name">Name.</param>
        /// <param name="path">Path.</param>
        /// <param name="isFullLimit">Is full limit.</param>
        public ProgramLimitation(int userID, string name, string path, bool isFullLimit)
        {
            this.UserID = userID;
            this.Name = name;
            this.Path = path;
            this.IsFullLimit = isFullLimit;
        }

        private ProgramLimitation()
        {
        }

        /// <inheritdoc/>
        public int ID { get; set; }

        /// <inheritdoc/>
        public int UserID { get; set; }

        /// <inheritdoc/>
        public string Name { get; set; }

        /// <inheritdoc/>
        public string Path { get; set; }

        /// <inheritdoc/>
        public bool IsFullLimit { get; set; }

        /// <summary>
        /// Gets or sets user.
        /// </summary>
        public virtual User User { get; set; }

        /// <summary>
        /// To string.
        /// </summary>
        /// <returns>String.</returns>
        public override string ToString()
        {
            return this.Name;
        }
    }
}
