//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSetting
    {
        internal TimeSetting(int userID, bool occasional, int minutes, bool orderly, TimeSpan fromTime, TimeSpan toTime)
        {
            UserID = userID;
            Occasional = occasional;
            Minutes = minutes;
            Orderly = orderly;
            FromTime = fromTime;
            ToTime = toTime;
        }

        public int ID { get; set; }
        public int UserID { get; set; }
        public bool Occasional { get; set; }
        public int Minutes { get; set; }
        public bool Orderly { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
