//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using ParentalControl.Interface.Database;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// User class.
    /// </summary>
    public partial class User : IUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        private User()
        {
            this.ProgramLimitations = new HashSet<ProgramLimitation>();
            this.WebLimitations = new HashSet<WebLimitation>();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        /// <param name="username">Username.</param>
        /// <param name="password">Password.</param>
        /// <param name="securityQuestion">Security question.</param>
        /// <param name="securityAnswer">Security answer.</param>
        internal User(string username, string password, string securityQuestion, string securityAnswer)
            : this()
        {
            this.Username = username;
            this.Password = password;
            this.SecurityQuestion = securityQuestion;
            this.SecurityAnswer = securityAnswer;
            this.IsTimeLimitInactive = false;
            this.IsTimeLimitOrderly = false;
            this.TimeLimitFromTime = default;
            this.TimeLimitToTime = default;
            this.TimeLimitOccasionalMinutes = 60;
            this.TimeLimitOccasionalDateTime = DateTime.Now;
            this.IsProgramLimitOrderly = false;
            this.ProgramLimitFromTime = default;
            this.ProgramLimitToTime = default;
            this.ProgramLimitOccasionalMinutes = 30;
            this.ProgramLimitOccasionalDateTime = DateTime.Now;
        }

        /// <inheritdoc/>
        public int ID { get; set; }

        /// <inheritdoc/>
        public string Username { get; set; }

        /// <inheritdoc/>
        public string Password { get; set; }

        /// <inheritdoc/>
        public string SecurityQuestion { get; set; }

        /// <inheritdoc/>
        public string SecurityAnswer { get; set; }

        /// <inheritdoc/>
        public bool IsTimeLimitInactive { get; set; }

        /// <inheritdoc/>
        public bool IsTimeLimitOrderly { get; set; }

        /// <inheritdoc/>
        public TimeSpan TimeLimitFromTime { get; set; }

        /// <inheritdoc/>
        public TimeSpan TimeLimitToTime { get; set; }

        /// <inheritdoc/>
        public int TimeLimitOccasionalMinutes { get; set; }

        /// <summary>
        /// Gets or sets time limitation occasional date time.
        /// </summary>
        public DateTime TimeLimitOccasionalDateTime { get; set; }

        /// <inheritdoc/>
        public bool IsProgramLimitOrderly { get; set; }

        /// <inheritdoc/>
        public TimeSpan ProgramLimitFromTime { get; set; }

        /// <inheritdoc/>
        public TimeSpan ProgramLimitToTime { get; set; }

        /// <inheritdoc/>
        public int ProgramLimitOccasionalMinutes { get; set; }

        /// <summary>
        /// Gets or sets program limitation occasional date time.
        /// </summary>
        public DateTime ProgramLimitOccasionalDateTime { get; set; }

        /// <summary>
        /// Gets or sets program limitations.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramLimitation> ProgramLimitations { get; set; }

        /// <summary>
        /// Gets or sets web limitations.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebLimitation> WebLimitations { get; set; }
    }
}
