//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using ParentalControl.Interface.Database;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// User class.
    /// </summary>
    public partial class User : IUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        private User()
        {
            this.ProgramLimitations = new HashSet<ProgramLimitation>();
            this.WebLimitations = new HashSet<WebLimitation>();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        /// <param name="username">Username.</param>
        /// <param name="password">Password.</param>
        /// <param name="securityQuestion">Security question.</param>
        /// <param name="securityAnswer">Security answer.</param>
        internal User(string username, string password, string securityQuestion, string securityAnswer)
            : this()
        {
            this.Username = username;
            this.Password = password;
            this.SecurityQuestion = securityQuestion;
            this.SecurityAnswer = securityAnswer;
            this.IsTimeLimitationActive = true;
            this.Occasional = false;
            this.Minutes = 0;
            this.Orderly = false;
            this.FromTime = default;
            this.ToTime = default;
        }

        /// <inheritdoc/>
        public int ID { get; set; }

        /// <inheritdoc/>
        public string Username { get; set; }

        /// <inheritdoc/>
        public string Password { get; set; }

        /// <inheritdoc/>
        public string SecurityQuestion { get; set; }

        /// <inheritdoc/>
        public string SecurityAnswer { get; set; }

        /// <inheritdoc/>
        public bool IsTimeLimitationActive { get; set; }

        /// <inheritdoc/>
        public bool Occasional { get; set; }

        /// <inheritdoc/>
        public int Minutes { get; set; }

        /// <inheritdoc/>
        public bool Orderly { get; set; }

        /// <inheritdoc/>
        public TimeSpan FromTime { get; set; }

        /// <inheritdoc/>
        public TimeSpan ToTime { get; set; }

        /// <summary>
        /// Gets or sets program limitations.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramLimitation> ProgramLimitations { get; set; }

        /// <summary>
        /// Gets or sets web limitations.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebLimitation> WebLimitations { get; set; }
    }
}
