//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using ParentalControl.Interface.Database;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Web limitation class.
    /// </summary>
    public partial class WebLimitation : IWebLimitation
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebLimitation"/> class.
        /// </summary>
        /// <param name="userID">UserID.</param>
        /// <param name="keywordID">KeywordID.</param>
        internal WebLimitation(int userID, int keywordID)
        {
            this.UserID = userID;
            this.KeywordID = keywordID;
        }

        private WebLimitation()
        {
        }

        /// <inheritdoc/>
        public int ID { get; set; }

        /// <inheritdoc/>
        public int UserID { get; set; }

        /// <inheritdoc/>
        public int KeywordID { get; set; }
    
        /// <summary>
        /// Gets or sets keyword.
        /// </summary>
        public virtual Keyword Keyword { get; set; }

        /// <summary>
        /// Gets or sets user.
        /// </summary>
        public virtual User User { get; set; }
    }
}
