//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentalControl.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSetting
    {
        internal WebSetting(int userID, int keywordID)
        {
            UserID = userID;
            KeywordID = keywordID;
        }

        public int ID { get; set; }
        public int UserID { get; set; }
        public int KeywordID { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual User User { get; set; }
    }
}
